services:
  - type: web
    name: tds2-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: AIPROXY_TOKEN
        sync: false
      - key: SECRET_PASSWORD
        sync: false 